
// Code generated by xlsx2proto.
// DO NOT EDIT!

package srvdata

import (
	"games.yol.com/win88/proto"
	"games.yol.com/win88/protocol/server"
)

var PBDB_FortuneGod_TurnRateMgr = &DB_FortuneGod_TurnRateMgr{pool: make(map[int32]*server.DB_FortuneGod_TurnRate), Datas: &server.DB_FortuneGod_TurnRateArray{}}

type DB_FortuneGod_TurnRateMgr struct {
	Datas *server.DB_FortuneGod_TurnRateArray
	pool  map[int32]*server.DB_FortuneGod_TurnRate
}

func (this *DB_FortuneGod_TurnRateMgr) unmarshal(data []byte) error {
	err := proto.Unmarshal(data, this.Datas)
	if err == nil {
		this.arrangeData()
	}
	return err
}

func (this *DB_FortuneGod_TurnRateMgr) reunmarshal(data []byte) error {
	newDatas := &server.DB_FortuneGod_TurnRateArray{}
	err := proto.Unmarshal(data, newDatas)
	if err == nil {
		for _, item := range newDatas.Arr {
			existItem := this.GetData(item.GetId())
			if existItem == nil {
				this.pool[item.GetId()] = item
				this.Datas.Arr = append(this.Datas.Arr, item)
			} else {
				*existItem = *item
			}
		}
	}
	return err
}

func (this *DB_FortuneGod_TurnRateMgr) arrangeData() {
	if this.Datas == nil {
		return
	}

	dataArr := this.Datas.GetArr()
	if dataArr == nil {
		return
	}

	for _, data := range dataArr {
		this.pool[data.GetId()] = data
	}
}

func (this *DB_FortuneGod_TurnRateMgr) GetData(id int32) *server.DB_FortuneGod_TurnRate {
	if data, ok := this.pool[id]; ok {
		return data
	}
	return nil
}

func init() {
	DataMgr.RegisteLoader("DB_FortuneGod_TurnRate.dat", &ProtobufDataLoader{dh: PBDB_FortuneGod_TurnRateMgr})
}
