
// Code generated by xlsx2proto.
// DO NOT EDIT!

package srvdata

import (
	"games.yol.com/win88/proto"
	"games.yol.com/win88/protocol/server"
)

var PBDB_FishMgr = &DB_FishMgr{pool: make(map[int32]*server.DB_Fish), Datas: &server.DB_FishArray{}}

type DB_FishMgr struct {
	Datas *server.DB_FishArray
	pool  map[int32]*server.DB_Fish
}

func (this *DB_FishMgr) unmarshal(data []byte) error {
	err := proto.Unmarshal(data, this.Datas)
	if err == nil {
		this.arrangeData()
	}
	return err
}

func (this *DB_FishMgr) reunmarshal(data []byte) error {
	newDatas := &server.DB_FishArray{}
	err := proto.Unmarshal(data, newDatas)
	if err == nil {
		for _, item := range newDatas.Arr {
			existItem := this.GetData(item.GetId())
			if existItem == nil {
				this.pool[item.GetId()] = item
				this.Datas.Arr = append(this.Datas.Arr, item)
			} else {
				*existItem = *item
			}
		}
	}
	return err
}

func (this *DB_FishMgr) arrangeData() {
	if this.Datas == nil {
		return
	}

	dataArr := this.Datas.GetArr()
	if dataArr == nil {
		return
	}

	for _, data := range dataArr {
		this.pool[data.GetId()] = data
	}
}

func (this *DB_FishMgr) GetData(id int32) *server.DB_Fish {
	if data, ok := this.pool[id]; ok {
		return data
	}
	return nil
}

func init() {
	DataMgr.RegisteLoader("DB_Fish.dat", &ProtobufDataLoader{dh: PBDB_FishMgr})
}
