
// Code generated by xlsx2proto.
// DO NOT EDIT!

package srvdata

import (
	"games.yol.com/win88/proto"
	"games.yol.com/win88/protocol/server"
)

var PBDB_GameFreeMgr = &DB_GameFreeMgr{pool: make(map[int32]*server.DB_GameFree), Datas: &server.DB_GameFreeArray{}}

type DB_GameFreeMgr struct {
	Datas *server.DB_GameFreeArray
	pool  map[int32]*server.DB_GameFree
}

func (this *DB_GameFreeMgr) unmarshal(data []byte) error {
	err := proto.Unmarshal(data, this.Datas)
	if err == nil {
		this.arrangeData()
	}
	return err
}

func (this *DB_GameFreeMgr) reunmarshal(data []byte) error {
	newDatas := &server.DB_GameFreeArray{}
	err := proto.Unmarshal(data, newDatas)
	if err == nil {
		for _, item := range newDatas.Arr {
			existItem := this.GetData(item.GetId())
			if existItem == nil {
				this.pool[item.GetId()] = item
				this.Datas.Arr = append(this.Datas.Arr, item)
			} else {
				*existItem = *item
			}
		}
	}
	return err
}

func (this *DB_GameFreeMgr) arrangeData() {
	if this.Datas == nil {
		return
	}

	dataArr := this.Datas.GetArr()
	if dataArr == nil {
		return
	}

	for _, data := range dataArr {
		this.pool[data.GetId()] = data
	}
}

func (this *DB_GameFreeMgr) GetData(id int32) *server.DB_GameFree {
	if data, ok := this.pool[id]; ok {
		return data
	}
	return nil
}

func init() {
	DataMgr.RegisteLoader("DB_GameFree.dat", &ProtobufDataLoader{dh: PBDB_GameFreeMgr})
}
