
// Code generated by xlsx2proto.
// DO NOT EDIT!

package srvdata

import (
	"games.yol.com/win88/proto"
	"games.yol.com/win88/protocol/server"
)

var PBDB_Policy151Mgr = &DB_Policy151Mgr{pool: make(map[int32]*server.DB_Policy151), Datas: &server.DB_Policy151Array{}}

type DB_Policy151Mgr struct {
	Datas *server.DB_Policy151Array
	pool  map[int32]*server.DB_Policy151
}

func (this *DB_Policy151Mgr) unmarshal(data []byte) error {
	err := proto.Unmarshal(data, this.Datas)
	if err == nil {
		this.arrangeData()
	}
	return err
}

func (this *DB_Policy151Mgr) reunmarshal(data []byte) error {
	newDatas := &server.DB_Policy151Array{}
	err := proto.Unmarshal(data, newDatas)
	if err == nil {
		for _, item := range newDatas.Arr {
			existItem := this.GetData(item.GetId())
			if existItem == nil {
				this.pool[item.GetId()] = item
				this.Datas.Arr = append(this.Datas.Arr, item)
			} else {
				*existItem = *item
			}
		}
	}
	return err
}

func (this *DB_Policy151Mgr) arrangeData() {
	if this.Datas == nil {
		return
	}

	dataArr := this.Datas.GetArr()
	if dataArr == nil {
		return
	}

	for _, data := range dataArr {
		this.pool[data.GetId()] = data
	}
}

func (this *DB_Policy151Mgr) GetData(id int32) *server.DB_Policy151 {
	if data, ok := this.pool[id]; ok {
		return data
	}
	return nil
}

func init() {
	DataMgr.RegisteLoader("DB_Policy151.dat", &ProtobufDataLoader{dh: PBDB_Policy151Mgr})
}
