// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.19.4
// source: shop.proto

package shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//操作结果
type OpResultCode int32

const (
	OpResultCode_OPRC_Sucess            OpResultCode = 0 //成功
	OpResultCode_OPRC_Error             OpResultCode = 1 //失败
	OpResultCode_OPRC_VCoinNotEnough    OpResultCode = 2 //V卡不够
	OpResultCode_OPRC_ExchangeLimit     OpResultCode = 3 //今日兑换已达上限，请明日再来
	OpResultCode_OPRC_ExchangeNotEnough OpResultCode = 4 //该物品已被兑换完
	OpResultCode_OPRC_ExchangeDataRtt   OpResultCode = 5 //输入信息有误
	OpResultCode_OPRC_ExchangeSoldOut   OpResultCode = 6 //该商品已下架
)

// Enum value maps for OpResultCode.
var (
	OpResultCode_name = map[int32]string{
		0: "OPRC_Sucess",
		1: "OPRC_Error",
		2: "OPRC_VCoinNotEnough",
		3: "OPRC_ExchangeLimit",
		4: "OPRC_ExchangeNotEnough",
		5: "OPRC_ExchangeDataRtt",
		6: "OPRC_ExchangeSoldOut",
	}
	OpResultCode_value = map[string]int32{
		"OPRC_Sucess":            0,
		"OPRC_Error":             1,
		"OPRC_VCoinNotEnough":    2,
		"OPRC_ExchangeLimit":     3,
		"OPRC_ExchangeNotEnough": 4,
		"OPRC_ExchangeDataRtt":   5,
		"OPRC_ExchangeSoldOut":   6,
	}
)

func (x OpResultCode) Enum() *OpResultCode {
	p := new(OpResultCode)
	*p = x
	return p
}

func (x OpResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_proto_enumTypes[0].Descriptor()
}

func (OpResultCode) Type() protoreflect.EnumType {
	return &file_shop_proto_enumTypes[0]
}

func (x OpResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpResultCode.Descriptor instead.
func (OpResultCode) EnumDescriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{0}
}

// 商城
type SPacketID int32

const (
	SPacketID_PACKET_SHOP_ZERO              SPacketID = 0    // 弃用消息号
	SPacketID_PACKET_CS_SHOP_INFO           SPacketID = 2500 //请求商品数据
	SPacketID_PACKET_SC_SHOP_INFO           SPacketID = 2501 //返回商品数据
	SPacketID_PACKET_CS_SHOP_ADLOOKED       SPacketID = 2502 //观看广告
	SPacketID_PACKET_SC_SHOP_ADLOOKED       SPacketID = 2503 //观看广告返回
	SPacketID_PACKET_CS_SHOP_VCPAYSHOP      SPacketID = 2504 //购买虚拟货币或者商品
	SPacketID_PACKET_SC_SHOP_VCPAYSHOP      SPacketID = 2505 //购买结果返回
	SPacketID_PACKET_CS_SHOP_EXCHANGERECORD SPacketID = 2506 //兑换记录
	SPacketID_PACKET_SC_SHOP_EXCHANGERECORD SPacketID = 2507
	SPacketID_PACKET_CS_SHOP_EXCHANGE       SPacketID = 2508 //兑换商品
	SPacketID_PACKET_SC_SHOP_EXCHANGE       SPacketID = 2509
	SPacketID_PACKET_CS_SHOP_EXCHANGELIST   SPacketID = 2510 //兑换商品列表
	SPacketID_PACKET_SC_SHOP_EXCHANGELIST   SPacketID = 2511
	/////Exchange
	SPacketID_SHOP_SC_GIVECOIN_INFO SPacketID = 2514 //通知赠送信息,先临时放到这个地方，其他协议需要合并
)

// Enum value maps for SPacketID.
var (
	SPacketID_name = map[int32]string{
		0:    "PACKET_SHOP_ZERO",
		2500: "PACKET_CS_SHOP_INFO",
		2501: "PACKET_SC_SHOP_INFO",
		2502: "PACKET_CS_SHOP_ADLOOKED",
		2503: "PACKET_SC_SHOP_ADLOOKED",
		2504: "PACKET_CS_SHOP_VCPAYSHOP",
		2505: "PACKET_SC_SHOP_VCPAYSHOP",
		2506: "PACKET_CS_SHOP_EXCHANGERECORD",
		2507: "PACKET_SC_SHOP_EXCHANGERECORD",
		2508: "PACKET_CS_SHOP_EXCHANGE",
		2509: "PACKET_SC_SHOP_EXCHANGE",
		2510: "PACKET_CS_SHOP_EXCHANGELIST",
		2511: "PACKET_SC_SHOP_EXCHANGELIST",
		2514: "SHOP_SC_GIVECOIN_INFO",
	}
	SPacketID_value = map[string]int32{
		"PACKET_SHOP_ZERO":              0,
		"PACKET_CS_SHOP_INFO":           2500,
		"PACKET_SC_SHOP_INFO":           2501,
		"PACKET_CS_SHOP_ADLOOKED":       2502,
		"PACKET_SC_SHOP_ADLOOKED":       2503,
		"PACKET_CS_SHOP_VCPAYSHOP":      2504,
		"PACKET_SC_SHOP_VCPAYSHOP":      2505,
		"PACKET_CS_SHOP_EXCHANGERECORD": 2506,
		"PACKET_SC_SHOP_EXCHANGERECORD": 2507,
		"PACKET_CS_SHOP_EXCHANGE":       2508,
		"PACKET_SC_SHOP_EXCHANGE":       2509,
		"PACKET_CS_SHOP_EXCHANGELIST":   2510,
		"PACKET_SC_SHOP_EXCHANGELIST":   2511,
		"SHOP_SC_GIVECOIN_INFO":         2514,
	}
)

func (x SPacketID) Enum() *SPacketID {
	p := new(SPacketID)
	*p = x
	return p
}

func (x SPacketID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SPacketID) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_proto_enumTypes[1].Descriptor()
}

func (SPacketID) Type() protoreflect.EnumType {
	return &file_shop_proto_enumTypes[1]
}

func (x SPacketID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SPacketID.Descriptor instead.
func (SPacketID) EnumDescriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{1}
}

//商品信息
type ShopInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//数据表数据
	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	//缓存数据
	AdLookedNum  int32 `protobuf:"varint,2,opt,name=AdLookedNum,proto3" json:"AdLookedNum,omitempty"`   //已经观看的次数
	AdReceiveNum int32 `protobuf:"varint,3,opt,name=AdReceiveNum,proto3" json:"AdReceiveNum,omitempty"` //已经领取的次数
	//  int32 RemainingTime = 4;//商品的剩余冷却时间
	LastLookTime int32 `protobuf:"varint,4,opt,name=LastLookTime,proto3" json:"LastLookTime,omitempty"` //商品上一次观看时间
	//展示数据
	RoleAdded         int32   `protobuf:"varint,5,opt,name=RoleAdded,proto3" json:"RoleAdded,omitempty"`                  //人物加成
	PetAdded          int32   `protobuf:"varint,6,opt,name=PetAdded,proto3" json:"PetAdded,omitempty"`                    //宠物加成
	ItemId            int32   `protobuf:"varint,7,opt,name=ItemId,proto3" json:"ItemId,omitempty"`                        //道具ID
	Page              int32   `protobuf:"varint,8,opt,name=Page,proto3" json:"Page,omitempty"`                            //页面 1，金币页面 2，钻石页面 3，道具页面
	Order             int32   `protobuf:"varint,9,opt,name=Order,proto3" json:"Order,omitempty"`                          //排序  页面内商品的位置排序
	Type              int32   `protobuf:"varint,10,opt,name=Type,proto3" json:"Type,omitempty"`                           // 类型 1，金币 2，钻石 3，道具类型1：用金币或者钻石购买 4.道具类型2：走充值购买 5，其他
	Location          []int32 `protobuf:"varint,11,rep,packed,name=Location,proto3" json:"Location,omitempty"`            // 显示位置 第1位，竖版大厅 第2位，Tienlen1级选场 第3位，捕鱼1级选场
	Picture           string  `protobuf:"bytes,12,opt,name=Picture,proto3" json:"Picture,omitempty"`                      // 图片id
	Name              string  `protobuf:"bytes,13,opt,name=Name,proto3" json:"Name,omitempty"`                            // 名称
	Ad                int32   `protobuf:"varint,14,opt,name=Ad,proto3" json:"Ad,omitempty"`                               //是否观看广告 1，是 2，不是
	AdTime            int32   `protobuf:"varint,15,opt,name=AdTime,proto3" json:"AdTime,omitempty"`                       // 观看几次广告
	RepeatTimes       int32   `protobuf:"varint,16,opt,name=RepeatTimes,proto3" json:"RepeatTimes,omitempty"`             // 领取次数
	CoolingTime       []int32 `protobuf:"varint,17,rep,packed,name=CoolingTime,proto3" json:"CoolingTime,omitempty"`      // 观看冷却时间
	Label             []int32 `protobuf:"varint,18,rep,packed,name=Label,proto3" json:"Label,omitempty"`                  // 标签
	Added             int32   `protobuf:"varint,19,opt,name=Added,proto3" json:"Added,omitempty"`                         // 加送百分比
	Amount            int32   `protobuf:"varint,20,opt,name=Amount,proto3" json:"Amount,omitempty"`                       // 货币金额
	Consume           int32   `protobuf:"varint,21,opt,name=Consume,proto3" json:"Consume,omitempty"`                     // 购买消耗类型 1，金币 2，钻石 3，美金 4，柬埔寨币
	ConsumptionAmount int32   `protobuf:"varint,22,opt,name=ConsumptionAmount,proto3" json:"ConsumptionAmount,omitempty"` // 消耗数量 加送百分比（比如加送10%，就配置110）
}

func (x *ShopInfo) Reset() {
	*x = ShopInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfo) ProtoMessage() {}

func (x *ShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfo.ProtoReflect.Descriptor instead.
func (*ShopInfo) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ShopInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopInfo) GetAdLookedNum() int32 {
	if x != nil {
		return x.AdLookedNum
	}
	return 0
}

func (x *ShopInfo) GetAdReceiveNum() int32 {
	if x != nil {
		return x.AdReceiveNum
	}
	return 0
}

func (x *ShopInfo) GetLastLookTime() int32 {
	if x != nil {
		return x.LastLookTime
	}
	return 0
}

func (x *ShopInfo) GetRoleAdded() int32 {
	if x != nil {
		return x.RoleAdded
	}
	return 0
}

func (x *ShopInfo) GetPetAdded() int32 {
	if x != nil {
		return x.PetAdded
	}
	return 0
}

func (x *ShopInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ShopInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ShopInfo) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *ShopInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ShopInfo) GetLocation() []int32 {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ShopInfo) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ShopInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopInfo) GetAd() int32 {
	if x != nil {
		return x.Ad
	}
	return 0
}

func (x *ShopInfo) GetAdTime() int32 {
	if x != nil {
		return x.AdTime
	}
	return 0
}

func (x *ShopInfo) GetRepeatTimes() int32 {
	if x != nil {
		return x.RepeatTimes
	}
	return 0
}

func (x *ShopInfo) GetCoolingTime() []int32 {
	if x != nil {
		return x.CoolingTime
	}
	return nil
}

func (x *ShopInfo) GetLabel() []int32 {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *ShopInfo) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *ShopInfo) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ShopInfo) GetConsume() int32 {
	if x != nil {
		return x.Consume
	}
	return 0
}

func (x *ShopInfo) GetConsumptionAmount() int32 {
	if x != nil {
		return x.ConsumptionAmount
	}
	return 0
}

//PACKET_CS_SHOP_INFO
type CSShopInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NowLocation int32 `protobuf:"varint,1,opt,name=NowLocation,proto3" json:"NowLocation,omitempty"` //0.通用 1.竖版 2.Tienlen 3.捕鱼
}

func (x *CSShopInfo) Reset() {
	*x = CSShopInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSShopInfo) ProtoMessage() {}

func (x *CSShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSShopInfo.ProtoReflect.Descriptor instead.
func (*CSShopInfo) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{1}
}

func (x *CSShopInfo) GetNowLocation() int32 {
	if x != nil {
		return x.NowLocation
	}
	return 0
}

//PACKET_SC_SHOP_INFO
type SCShopInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*ShopInfo `protobuf:"bytes,1,rep,name=Infos,proto3" json:"Infos,omitempty"` //商品信息
}

func (x *SCShopInfo) Reset() {
	*x = SCShopInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCShopInfo) ProtoMessage() {}

func (x *SCShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCShopInfo.ProtoReflect.Descriptor instead.
func (*SCShopInfo) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{2}
}

func (x *SCShopInfo) GetInfos() []*ShopInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

//PACKET_CS_SHOP_ADLOOKED
type CSAdLooked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LookedResult int32 `protobuf:"varint,1,opt,name=LookedResult,proto3" json:"LookedResult,omitempty"` //0.观看成功 //失败或者中断不用告知
	ShopId       int32 `protobuf:"varint,2,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
}

func (x *CSAdLooked) Reset() {
	*x = CSAdLooked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSAdLooked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSAdLooked) ProtoMessage() {}

func (x *CSAdLooked) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSAdLooked.ProtoReflect.Descriptor instead.
func (*CSAdLooked) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{3}
}

func (x *CSAdLooked) GetLookedResult() int32 {
	if x != nil {
		return x.LookedResult
	}
	return 0
}

func (x *CSAdLooked) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

//PACKET_SC_SHOP_ADLOOKED
type SCAdLooked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode  OpResultCode `protobuf:"varint,1,opt,name=RetCode,proto3,enum=shop.OpResultCode" json:"RetCode,omitempty"`
	ShopInfo *ShopInfo    `protobuf:"bytes,2,opt,name=ShopInfo,proto3" json:"ShopInfo,omitempty"` //刷新商品信息
}

func (x *SCAdLooked) Reset() {
	*x = SCAdLooked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCAdLooked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCAdLooked) ProtoMessage() {}

func (x *SCAdLooked) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCAdLooked.ProtoReflect.Descriptor instead.
func (*SCAdLooked) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{4}
}

func (x *SCAdLooked) GetRetCode() OpResultCode {
	if x != nil {
		return x.RetCode
	}
	return OpResultCode_OPRC_Sucess
}

func (x *SCAdLooked) GetShopInfo() *ShopInfo {
	if x != nil {
		return x.ShopInfo
	}
	return nil
}

//PACKET_CS_SHOP_VCPAYSHOP
type CSVCPayShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int32 `protobuf:"varint,1,opt,name=ShopId,proto3" json:"ShopId,omitempty"` //商品Id
}

func (x *CSVCPayShop) Reset() {
	*x = CSVCPayShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSVCPayShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSVCPayShop) ProtoMessage() {}

func (x *CSVCPayShop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSVCPayShop.ProtoReflect.Descriptor instead.
func (*CSVCPayShop) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{5}
}

func (x *CSVCPayShop) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

//PACKET_SC_SHOP_VCPAYSHOP
type SCVCPayShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode  OpResultCode `protobuf:"varint,1,opt,name=RetCode,proto3,enum=shop.OpResultCode" json:"RetCode,omitempty"`
	ShopInfo *ShopInfo    `protobuf:"bytes,2,opt,name=ShopInfo,proto3" json:"ShopInfo,omitempty"` //刷新商品信息
}

func (x *SCVCPayShop) Reset() {
	*x = SCVCPayShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCVCPayShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCVCPayShop) ProtoMessage() {}

func (x *SCVCPayShop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCVCPayShop.ProtoReflect.Descriptor instead.
func (*SCVCPayShop) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{6}
}

func (x *SCVCPayShop) GetRetCode() OpResultCode {
	if x != nil {
		return x.RetCode
	}
	return OpResultCode_OPRC_Sucess
}

func (x *SCVCPayShop) GetShopInfo() *ShopInfo {
	if x != nil {
		return x.ShopInfo
	}
	return nil
}

type SCNotifyGiveCoinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiveCoin int64 `protobuf:"varint,1,opt,name=GiveCoin,proto3" json:"GiveCoin,omitempty"` //赠送金币
	GiveTag  int32 `protobuf:"varint,2,opt,name=GiveTag,proto3" json:"GiveTag,omitempty"`   //赠送类型，需要对应关系
}

func (x *SCNotifyGiveCoinInfo) Reset() {
	*x = SCNotifyGiveCoinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCNotifyGiveCoinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCNotifyGiveCoinInfo) ProtoMessage() {}

func (x *SCNotifyGiveCoinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCNotifyGiveCoinInfo.ProtoReflect.Descriptor instead.
func (*SCNotifyGiveCoinInfo) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{7}
}

func (x *SCNotifyGiveCoinInfo) GetGiveCoin() int64 {
	if x != nil {
		return x.GiveCoin
	}
	return 0
}

func (x *SCNotifyGiveCoinInfo) GetGiveTag() int32 {
	if x != nil {
		return x.GiveTag
	}
	return 0
}

//商城兑换记录
//PACKET_CS_SHOP_EXCHANGERECORD
type CSShopExchangeRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNo int32 `protobuf:"varint,1,opt,name=PageNo,proto3" json:"PageNo,omitempty"` //当前页
}

func (x *CSShopExchangeRecord) Reset() {
	*x = CSShopExchangeRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSShopExchangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSShopExchangeRecord) ProtoMessage() {}

func (x *CSShopExchangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSShopExchangeRecord.ProtoReflect.Descriptor instead.
func (*CSShopExchangeRecord) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{8}
}

func (x *CSShopExchangeRecord) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

type ShopExchangeRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTs int64  `protobuf:"varint,1,opt,name=CreateTs,proto3" json:"CreateTs,omitempty"` //订单创建日期
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`          //名称
	OrderId  string `protobuf:"bytes,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`    //订单号
	State    int32  `protobuf:"varint,4,opt,name=State,proto3" json:"State,omitempty"`       //状态 0.等待审核 1.已通过 2.未通过
	Remark   string `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty"`      //订单备注
}

func (x *ShopExchangeRecord) Reset() {
	*x = ShopExchangeRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopExchangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopExchangeRecord) ProtoMessage() {}

func (x *ShopExchangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopExchangeRecord.ProtoReflect.Descriptor instead.
func (*ShopExchangeRecord) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{9}
}

func (x *ShopExchangeRecord) GetCreateTs() int64 {
	if x != nil {
		return x.CreateTs
	}
	return 0
}

func (x *ShopExchangeRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopExchangeRecord) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShopExchangeRecord) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ShopExchangeRecord) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

//PACKET_SC_SHOP_EXCHANGERECORD
type SCShopExchangeRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNo   int32                 `protobuf:"varint,1,opt,name=PageNo,proto3" json:"PageNo,omitempty"`     //当前页
	PageSize int32                 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"` //每页数量
	PageSum  int32                 `protobuf:"varint,3,opt,name=PageSum,proto3" json:"PageSum,omitempty"`   //总页数
	Infos    []*ShopExchangeRecord `protobuf:"bytes,4,rep,name=Infos,proto3" json:"Infos,omitempty"`        //刷新商品信息
}

func (x *SCShopExchangeRecord) Reset() {
	*x = SCShopExchangeRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCShopExchangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCShopExchangeRecord) ProtoMessage() {}

func (x *SCShopExchangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCShopExchangeRecord.ProtoReflect.Descriptor instead.
func (*SCShopExchangeRecord) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{10}
}

func (x *SCShopExchangeRecord) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *SCShopExchangeRecord) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SCShopExchangeRecord) GetPageSum() int32 {
	if x != nil {
		return x.PageSum
	}
	return 0
}

func (x *SCShopExchangeRecord) GetInfos() []*ShopExchangeRecord {
	if x != nil {
		return x.Infos
	}
	return nil
}

//商城兑换
//PACKET_CS_SHOP_EXCHANGERECORD
type CSShopExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId  int32  `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`  //商品ID
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"` //兑换人姓名
	Mobile   string `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`     //兑换人手机号
	Comment  string `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`   //备注信息
}

func (x *CSShopExchange) Reset() {
	*x = CSShopExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSShopExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSShopExchange) ProtoMessage() {}

func (x *CSShopExchange) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSShopExchange.ProtoReflect.Descriptor instead.
func (*CSShopExchange) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{11}
}

func (x *CSShopExchange) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CSShopExchange) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CSShopExchange) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CSShopExchange) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SCShopExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode  OpResultCode `protobuf:"varint,1,opt,name=RetCode,proto3,enum=shop.OpResultCode" json:"RetCode,omitempty"`
	CreateTs int64        `protobuf:"varint,2,opt,name=CreateTs,proto3" json:"CreateTs,omitempty"` //订单创建日期
	OrderId  string       `protobuf:"bytes,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`    //订单号
}

func (x *SCShopExchange) Reset() {
	*x = SCShopExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCShopExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCShopExchange) ProtoMessage() {}

func (x *SCShopExchange) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCShopExchange.ProtoReflect.Descriptor instead.
func (*SCShopExchange) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{12}
}

func (x *SCShopExchange) GetRetCode() OpResultCode {
	if x != nil {
		return x.RetCode
	}
	return OpResultCode_OPRC_Sucess
}

func (x *SCShopExchange) GetCreateTs() int64 {
	if x != nil {
		return x.CreateTs
	}
	return 0
}

func (x *SCShopExchange) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

//PACKET_CS_SHOP_EXCHANGELIST
type CSShopExchangeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSShopExchangeList) Reset() {
	*x = CSShopExchangeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSShopExchangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSShopExchangeList) ProtoMessage() {}

func (x *CSShopExchangeList) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSShopExchangeList.ProtoReflect.Descriptor instead.
func (*CSShopExchangeList) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{13}
}

type ShopExchangeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         int32  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`                 // 类型 1，话费2，实物
	Picture      string `protobuf:"bytes,2,opt,name=Picture,proto3" json:"Picture,omitempty"`            // 图片
	Name         string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                  // 名称
	NeedNum      int32  `protobuf:"varint,4,opt,name=NeedNum,proto3" json:"NeedNum,omitempty"`           // 消耗V卡
	Rule         string `protobuf:"bytes,5,opt,name=Rule,proto3" json:"Rule,omitempty"`                  //规则说明
	GoodsId      int32  `protobuf:"varint,6,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`           //商品ID
	ShopLimit    int32  `protobuf:"varint,7,opt,name=ShopLimit,proto3" json:"ShopLimit,omitempty"`       // 剩余总数
	DayMaxLimit  int32  `protobuf:"varint,8,opt,name=DayMaxLimit,proto3" json:"DayMaxLimit,omitempty"`   // 单日限购总数
	DayPlayLimit int32  `protobuf:"varint,9,opt,name=DayPlayLimit,proto3" json:"DayPlayLimit,omitempty"` // 个人单日购买
}

func (x *ShopExchangeInfo) Reset() {
	*x = ShopExchangeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopExchangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopExchangeInfo) ProtoMessage() {}

func (x *ShopExchangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopExchangeInfo.ProtoReflect.Descriptor instead.
func (*ShopExchangeInfo) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{14}
}

func (x *ShopExchangeInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ShopExchangeInfo) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ShopExchangeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopExchangeInfo) GetNeedNum() int32 {
	if x != nil {
		return x.NeedNum
	}
	return 0
}

func (x *ShopExchangeInfo) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *ShopExchangeInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ShopExchangeInfo) GetShopLimit() int32 {
	if x != nil {
		return x.ShopLimit
	}
	return 0
}

func (x *ShopExchangeInfo) GetDayMaxLimit() int32 {
	if x != nil {
		return x.DayMaxLimit
	}
	return 0
}

func (x *ShopExchangeInfo) GetDayPlayLimit() int32 {
	if x != nil {
		return x.DayPlayLimit
	}
	return 0
}

type SCShopExchangeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode OpResultCode        `protobuf:"varint,1,opt,name=RetCode,proto3,enum=shop.OpResultCode" json:"RetCode,omitempty"`
	Infos   []*ShopExchangeInfo `protobuf:"bytes,2,rep,name=Infos,proto3" json:"Infos,omitempty"` //兑换商品列表
}

func (x *SCShopExchangeList) Reset() {
	*x = SCShopExchangeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCShopExchangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCShopExchangeList) ProtoMessage() {}

func (x *SCShopExchangeList) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCShopExchangeList.ProtoReflect.Descriptor instead.
func (*SCShopExchangeList) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{15}
}

func (x *SCShopExchangeList) GetRetCode() OpResultCode {
	if x != nil {
		return x.RetCode
	}
	return OpResultCode_OPRC_Sucess
}

func (x *SCShopExchangeList) GetInfos() []*ShopExchangeInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_shop_proto protoreflect.FileDescriptor

var file_shop_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x68,
	0x6f, 0x70, 0x22, 0xd6, 0x04, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x41, 0x64, 0x4c, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x41, 0x64, 0x4c, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x4e, 0x75,
	0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x41, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x6f,
	0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x4c, 0x61, 0x73,
	0x74, 0x4c, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x6f, 0x6c,
	0x65, 0x41, 0x64, 0x64, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x6f,
	0x6c, 0x65, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x41, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x41, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x41, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x11, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0b, 0x43, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x12, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x65, 0x64, 0x18, 0x13,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x2c, 0x0a,
	0x11, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x0a, 0x43,
	0x53, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x6f, 0x77,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x4e, 0x6f, 0x77, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x0a, 0x53,
	0x43, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x05, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22,
	0x48, 0x0a, 0x0a, 0x43, 0x53, 0x41, 0x64, 0x4c, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x4c, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x4c, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x0a, 0x53, 0x43, 0x41,
	0x64, 0x4c, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x4f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x52, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x53, 0x56, 0x43, 0x50, 0x61, 0x79, 0x53, 0x68, 0x6f, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x0b, 0x53, 0x43, 0x56, 0x43,
	0x50, 0x61, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x4f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x52, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x4c, 0x0a, 0x14, 0x53, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x69, 0x76,
	0x65, 0x43, 0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x69, 0x76,
	0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x47, 0x69, 0x76,
	0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x69, 0x76, 0x65, 0x54, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x47, 0x69, 0x76, 0x65, 0x54, 0x61, 0x67, 0x22,
	0x2e, 0x0a, 0x14, 0x43, 0x53, 0x53, 0x68, 0x6f, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x22,
	0x8c, 0x01, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x94,
	0x01, 0x0a, 0x14, 0x53, 0x43, 0x53, 0x68, 0x6f, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x61,
	0x67, 0x65, 0x53, 0x75, 0x6d, 0x12, 0x2e, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x05,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x78, 0x0a, 0x0e, 0x43, 0x53, 0x53, 0x68, 0x6f, 0x70, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x74, 0x0a, 0x0e, 0x53, 0x43, 0x53, 0x68, 0x6f, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x53, 0x53, 0x68, 0x6f, 0x70, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x80, 0x02, 0x0a, 0x10,
	0x53, 0x68, 0x6f, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x4e, 0x65, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x52, 0x75, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x75, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x68,
	0x6f, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53,
	0x68, 0x6f, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61, 0x79, 0x4d,
	0x61, 0x78, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x44,
	0x61, 0x79, 0x4d, 0x61, 0x78, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x61,
	0x79, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x44, 0x61, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x70,
	0x0a, 0x12, 0x53, 0x43, 0x53, 0x68, 0x6f, 0x70, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x4f, 0x70, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x2a, 0xb0, 0x01, 0x0a, 0x0c, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x52, 0x43, 0x5f, 0x53, 0x75, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x50, 0x52, 0x43, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x50, 0x52, 0x43, 0x5f, 0x56, 0x43, 0x6f, 0x69, 0x6e,
	0x4e, 0x6f, 0x74, 0x45, 0x6e, 0x6f, 0x75, 0x67, 0x68, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x4f,
	0x50, 0x52, 0x43, 0x5f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x50, 0x52, 0x43, 0x5f, 0x45, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x6e, 0x6f, 0x75, 0x67, 0x68, 0x10, 0x04, 0x12,
	0x18, 0x0a, 0x14, 0x4f, 0x50, 0x52, 0x43, 0x5f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x74, 0x74, 0x10, 0x05, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x50, 0x52,
	0x43, 0x5f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x6f, 0x6c, 0x64, 0x4f, 0x75,
	0x74, 0x10, 0x06, 0x2a, 0xb3, 0x03, 0x0a, 0x09, 0x53, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x48, 0x4f, 0x50,
	0x5f, 0x5a, 0x45, 0x52, 0x4f, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x13, 0x50, 0x41, 0x43, 0x4b, 0x45,
	0x54, 0x5f, 0x43, 0x53, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0xc4,
	0x13, 0x12, 0x18, 0x0a, 0x13, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x5f, 0x53,
	0x48, 0x4f, 0x50, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0xc5, 0x13, 0x12, 0x1c, 0x0a, 0x17, 0x50,
	0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x43, 0x53, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x41, 0x44,
	0x4c, 0x4f, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0xc6, 0x13, 0x12, 0x1c, 0x0a, 0x17, 0x50, 0x41, 0x43,
	0x4b, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x41, 0x44, 0x4c, 0x4f,
	0x4f, 0x4b, 0x45, 0x44, 0x10, 0xc7, 0x13, 0x12, 0x1d, 0x0a, 0x18, 0x50, 0x41, 0x43, 0x4b, 0x45,
	0x54, 0x5f, 0x43, 0x53, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x56, 0x43, 0x50, 0x41, 0x59, 0x53,
	0x48, 0x4f, 0x50, 0x10, 0xc8, 0x13, 0x12, 0x1d, 0x0a, 0x18, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54,
	0x5f, 0x53, 0x43, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x56, 0x43, 0x50, 0x41, 0x59, 0x53, 0x48,
	0x4f, 0x50, 0x10, 0xc9, 0x13, 0x12, 0x22, 0x0a, 0x1d, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f,
	0x43, 0x53, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x10, 0xca, 0x13, 0x12, 0x22, 0x0a, 0x1d, 0x50, 0x41, 0x43,
	0x4b, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x45, 0x58, 0x43, 0x48,
	0x41, 0x4e, 0x47, 0x45, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x10, 0xcb, 0x13, 0x12, 0x1c, 0x0a,
	0x17, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x43, 0x53, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f,
	0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0xcc, 0x13, 0x12, 0x1c, 0x0a, 0x17, 0x50,
	0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x45, 0x58,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0xcd, 0x13, 0x12, 0x20, 0x0a, 0x1b, 0x50, 0x41, 0x43,
	0x4b, 0x45, 0x54, 0x5f, 0x43, 0x53, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x45, 0x58, 0x43, 0x48,
	0x41, 0x4e, 0x47, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x10, 0xce, 0x13, 0x12, 0x20, 0x0a, 0x1b, 0x50,
	0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x5f, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x45, 0x58,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x10, 0xcf, 0x13, 0x12, 0x1a, 0x0a,
	0x15, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x53, 0x43, 0x5f, 0x47, 0x49, 0x56, 0x45, 0x43, 0x4f, 0x49,
	0x4e, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0xd2, 0x13, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x73,
	0x68, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shop_proto_rawDescOnce sync.Once
	file_shop_proto_rawDescData = file_shop_proto_rawDesc
)

func file_shop_proto_rawDescGZIP() []byte {
	file_shop_proto_rawDescOnce.Do(func() {
		file_shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_shop_proto_rawDescData)
	})
	return file_shop_proto_rawDescData
}

var file_shop_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_shop_proto_goTypes = []interface{}{
	(OpResultCode)(0),            // 0: shop.OpResultCode
	(SPacketID)(0),               // 1: shop.SPacketID
	(*ShopInfo)(nil),             // 2: shop.ShopInfo
	(*CSShopInfo)(nil),           // 3: shop.CSShopInfo
	(*SCShopInfo)(nil),           // 4: shop.SCShopInfo
	(*CSAdLooked)(nil),           // 5: shop.CSAdLooked
	(*SCAdLooked)(nil),           // 6: shop.SCAdLooked
	(*CSVCPayShop)(nil),          // 7: shop.CSVCPayShop
	(*SCVCPayShop)(nil),          // 8: shop.SCVCPayShop
	(*SCNotifyGiveCoinInfo)(nil), // 9: shop.SCNotifyGiveCoinInfo
	(*CSShopExchangeRecord)(nil), // 10: shop.CSShopExchangeRecord
	(*ShopExchangeRecord)(nil),   // 11: shop.ShopExchangeRecord
	(*SCShopExchangeRecord)(nil), // 12: shop.SCShopExchangeRecord
	(*CSShopExchange)(nil),       // 13: shop.CSShopExchange
	(*SCShopExchange)(nil),       // 14: shop.SCShopExchange
	(*CSShopExchangeList)(nil),   // 15: shop.CSShopExchangeList
	(*ShopExchangeInfo)(nil),     // 16: shop.ShopExchangeInfo
	(*SCShopExchangeList)(nil),   // 17: shop.SCShopExchangeList
}
var file_shop_proto_depIdxs = []int32{
	2,  // 0: shop.SCShopInfo.Infos:type_name -> shop.ShopInfo
	0,  // 1: shop.SCAdLooked.RetCode:type_name -> shop.OpResultCode
	2,  // 2: shop.SCAdLooked.ShopInfo:type_name -> shop.ShopInfo
	0,  // 3: shop.SCVCPayShop.RetCode:type_name -> shop.OpResultCode
	2,  // 4: shop.SCVCPayShop.ShopInfo:type_name -> shop.ShopInfo
	11, // 5: shop.SCShopExchangeRecord.Infos:type_name -> shop.ShopExchangeRecord
	0,  // 6: shop.SCShopExchange.RetCode:type_name -> shop.OpResultCode
	0,  // 7: shop.SCShopExchangeList.RetCode:type_name -> shop.OpResultCode
	16, // 8: shop.SCShopExchangeList.Infos:type_name -> shop.ShopExchangeInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_shop_proto_init() }
func file_shop_proto_init() {
	if File_shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSShopInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCShopInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSAdLooked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCAdLooked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSVCPayShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCVCPayShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCNotifyGiveCoinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSShopExchangeRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopExchangeRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCShopExchangeRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSShopExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCShopExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSShopExchangeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopExchangeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCShopExchangeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shop_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shop_proto_goTypes,
		DependencyIndexes: file_shop_proto_depIdxs,
		EnumInfos:         file_shop_proto_enumTypes,
		MessageInfos:      file_shop_proto_msgTypes,
	}.Build()
	File_shop_proto = out.File
	file_shop_proto_rawDesc = nil
	file_shop_proto_goTypes = nil
	file_shop_proto_depIdxs = nil
}
